version: '3'
services:
  react: #サービス名
    build:
      context: .
      dockerfile: ./docker/react/Dockerfile
    tty: true #コンテナの起動永続化
    volumes:
      - .:/react/src/work #マウントディレクトリ指定
    command: sh -c "cd frontend && yarn start"
    ports:
      - "3000:3000"
  go:
    build:
      context: .
      dockerfile: ./docker/golang/Dockerfile
    container_name: go_container
    ports:
      - 8080:8080
    tty: true